"""add telemetry table for trip tracking

Revision ID: 4ebfadd041b4
Revises: fa9e0af66d26
Create Date: 2025-11-18 12:04:55.318546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ebfadd041b4'
down_revision: Union[str, Sequence[str], None] = 'fa9e0af66d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    telemetry_exists = 'telemetry' in inspector.get_table_names()

    if not telemetry_exists:
        # Fresh install: create telemetry table directly with the new schema
        op.create_table(
            'telemetry',
            sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
            sa.Column('vehicle_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('trip_id', postgresql.UUID(as_uuid=True), nullable=True),
            sa.Column('latitude', sa.Float(), nullable=False),
            sa.Column('longitude', sa.Float(), nullable=False),
            sa.Column('timestamp', sa.DateTime(), nullable=False),
            sa.Column('speed_kmh', sa.Float(), nullable=True),
            sa.Column('heading', sa.Float(), nullable=True),
            sa.Column('ignition', sa.Boolean(), nullable=True),
            sa.Column('fuel_level', sa.Float(), nullable=True),
            sa.Column('rpm', sa.Integer(), nullable=True),
            sa.Column('temperature', sa.Float(), nullable=True),
            sa.Column('odometer', sa.Float(), nullable=True),
            sa.Column('battery_voltage', sa.Float(), nullable=True),
            sa.Column('signal_strength', sa.Integer(), nullable=True),
            sa.Column('raw_payload', sa.String(), nullable=True),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id']),
            sa.ForeignKeyConstraint(['trip_id'], ['trips.id']),
        )
        op.create_index('idx_telemetry_vehicle_timestamp', 'telemetry', ['vehicle_id', 'timestamp'], unique=False)
        op.create_index('idx_telemetry_trip_timestamp', 'telemetry', ['trip_id', 'timestamp'], unique=False)
        op.create_index(op.f('ix_telemetry_timestamp'), 'telemetry', ['timestamp'], unique=False)
        op.create_index(op.f('ix_telemetry_trip_id'), 'telemetry', ['trip_id'], unique=False)
        op.create_index(op.f('ix_telemetry_vehicle_id'), 'telemetry', ['vehicle_id'], unique=False)
        return

    op.add_column('telemetry', sa.Column('vehicle_id', sa.UUID(), nullable=False))
    op.add_column('telemetry', sa.Column('trip_id', sa.UUID(), nullable=True))
    op.add_column('telemetry', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('telemetry', 'speed_kmh',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('telemetry', 'heading',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('telemetry', 'fuel_level',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('telemetry', 'temperature',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('telemetry', 'odometer',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('telemetry', 'battery_voltage',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('telemetry', 'raw_payload',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('telemetry', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('telemetry', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_telemetry_imei'), table_name='telemetry')
    op.drop_index(op.f('idx_telemetry_imei_timestamp'), table_name='telemetry')
    op.drop_index(op.f('idx_telemetry_timestamp'), table_name='telemetry')
    op.create_index('idx_telemetry_trip_timestamp', 'telemetry', ['trip_id', 'timestamp'], unique=False)
    op.create_index('idx_telemetry_vehicle_timestamp', 'telemetry', ['vehicle_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_timestamp'), 'telemetry', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_trip_id'), 'telemetry', ['trip_id'], unique=False)
    op.create_index(op.f('ix_telemetry_vehicle_id'), 'telemetry', ['vehicle_id'], unique=False)
    op.create_foreign_key(None, 'telemetry', 'trips', ['trip_id'], ['id'])
    op.create_foreign_key(None, 'telemetry', 'vehicles', ['vehicle_id'], ['id'])
    op.drop_column('telemetry', 'imei')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('imei', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'telemetry', type_='foreignkey')
    op.drop_constraint(None, 'telemetry', type_='foreignkey')
    op.drop_index(op.f('ix_telemetry_vehicle_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_trip_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_timestamp'), table_name='telemetry')
    op.drop_index('idx_telemetry_vehicle_timestamp', table_name='telemetry')
    op.drop_index('idx_telemetry_trip_timestamp', table_name='telemetry')
    op.create_index(op.f('idx_telemetry_timestamp'), 'telemetry', ['timestamp'], unique=False)
    op.create_index(op.f('idx_telemetry_imei_timestamp'), 'telemetry', ['imei', 'timestamp'], unique=False)
    op.create_index(op.f('idx_telemetry_imei'), 'telemetry', ['imei'], unique=False)
    op.alter_column('telemetry', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('telemetry', 'id',
               existing_type=sa.UUID(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('telemetry', 'raw_payload',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('telemetry', 'battery_voltage',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('telemetry', 'odometer',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('telemetry', 'temperature',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('telemetry', 'fuel_level',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('telemetry', 'heading',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('telemetry', 'speed_kmh',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('telemetry', 'updated_at')
    op.drop_column('telemetry', 'trip_id')
    op.drop_column('telemetry', 'vehicle_id')
    # ### end Alembic commands ###
