"""Create initial tables

Revision ID: fa9e0af66d26
Revises: 
Create Date: 2025-11-17 16:44:03.364597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa9e0af66d26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TECHNICIAN', 'CLIENT', 'COMPANY', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('hubs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='subscriptiontier'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technicians',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hub_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('imei', sa.String(length=20), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'RETIRED', name='vehiclestatus'), nullable=False),
    sa.Column('hub_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_imei'), 'vehicles', ['imei'], unique=True)
    op.create_index(op.f('ix_vehicles_license_plate'), 'vehicles', ['license_plate'], unique=True)
    op.create_table('devices',
    sa.Column('imei', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'FAULTY', 'UNASSIGNED', name='devicestatus'), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_imei'), 'devices', ['imei'], unique=True)
    op.create_table('trips',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('start_location', sa.String(length=255), nullable=True),
    sa.Column('end_location', sa.String(length=255), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('max_speed', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_end_time'), 'trips', ['end_time'], unique=False)
    op.create_index(op.f('ix_trips_start_time'), 'trips', ['start_time'], unique=False)

    # Guard legacy telemetry teardown so fresh installs succeed
    bind = op.get_bind()
    inspector = inspect(bind)
    telemetry_table_exists = 'telemetry' in inspector.get_table_names()
    if telemetry_table_exists:
        existing_indexes = {idx['name'] for idx in inspector.get_indexes('telemetry')}
        for index_name in (
            op.f('idx_telemetry_imei'),
            op.f('idx_telemetry_imei_timestamp'),
            op.f('idx_telemetry_timestamp'),
        ):
            if index_name in existing_indexes:
                op.drop_index(index_name, table_name='telemetry')
        op.drop_table('telemetry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('imei', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('speed_kmh', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('heading', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('fuel_level', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('rpm', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('ignition', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('odometer', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('battery_voltage', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('signal_strength', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_payload', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('telemetry_pkey'))
    )
    op.create_index(op.f('idx_telemetry_timestamp'), 'telemetry', ['timestamp'], unique=False)
    op.create_index(op.f('idx_telemetry_imei_timestamp'), 'telemetry', ['imei', 'timestamp'], unique=False)
    op.create_index(op.f('idx_telemetry_imei'), 'telemetry', ['imei'], unique=False)
    op.drop_index(op.f('ix_trips_start_time'), table_name='trips')
    op.drop_index(op.f('ix_trips_end_time'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_devices_imei'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_vehicles_license_plate'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_imei'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('technicians')
    op.drop_table('subscriptions')
    op.drop_table('hubs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
